name: json_dynamic_widget_plugin_markdown
description: A plugin to the JSON Dynamic Widget to provide support for Markdown
homepage: https://github.com/peiffer-innovations/json_dynamic_widget_plugin_markdown

version: 3.0.0

environment:
  sdk: ">=2.16.0 <3.0.0"

analyzer:
  exclude: [lib/generated/**]

dependencies:
  child_builder: ^2.0.0+3
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.10
  intl: ^0.17.0
  json_class: ^2.1.2+4
  json_dynamic_widget: ^5.0.0
  json_theme: ^4.0.0
  logging: ^1.0.2
  meta: ^1.7.0
  uuid: ^3.0.6

# dependency_overrides:
#   json_theme:
#     path: ../json_theme
#   json_dynamic_widget:
#     path: ../json_dynamic_widget

false_secrets:
  - example/web/index.html

dev_dependencies:
  flutter_test:
    sdk: flutter
