name: "json_dynamic_widget_plugin_markdown"
description: "A plugin to the JSON Dynamic Widget to provide support for Markdown"
homepage: "https://github.com/peiffer-innovations/json_dynamic_widget_plugin_markdown"
version: "5.0.1+3"

environment:
  sdk: ">=3.0.0 <4.0.0"

analyzer:
  exclude:
    - "lib/generated/**"
    - "lib/**/*.g.dart"

dependencies:
  child_builder: "^2.0.2"
  flutter:
    sdk: "flutter"
  flutter_markdown: "^0.7.6+2"
  intl: ">=0.18.0<1.0.0"
  json_class: "^3.0.1"
  json_dynamic_widget: "^9.0.0+1"
  json_theme: "^8.0.0"
  logging: "^1.3.0"
  markdown: "^7.3.0"
  meta: "^1.12.0"
  uuid: "^4.5.1"

false_secrets:
  - "example/web/index.html"

dev_dependencies:
  build_runner: "^2.4.15"
  flutter_lints: "^5.0.0"
  flutter_test:
    sdk: "flutter"
  json_dynamic_widget_codegen: "^2.1.0"

permittedLicenses:
  - "Apache-2.0"
  - "BSD-2-Clause"
  - "BSD-3-Clause"
  - "MIT"
  - "MIT-Modern-Variant"
  - "MPL-2.0"
  - "Zlib"

packageLicenseOverride:
  flutter: "BSD-3-Clause"
  flutter_driver: "BSD-3-Clause"
  flutter_goldens: "BSD-3-Clause"
  flutter_localizations: "BSD-3-Clause"
  flutter_web_plugins: "BSD-3-Clause"
  flutter_test: "BSD-3-Clause"
  fuchsia_remote_debug_protocol: "BSD-3-Clause"
  integration_test: "BSD-3-Clause"
  rxdart: "Apache-2.0"

ignore_updates:
  - "archive"
  - "async"
  - "boolean_selector"
  - "characters"
  - "charcode"
  - "collection"
  - "clock"
  - "crypto"
  - "fake_async"
  - "file"
  - "matcher"
  - "material_color_utilities"
  - "meta"
  - "path"
  - "source_span"
  - "stack_trace"
  - "stream_channel"
  - "string_scanner"
  - "sync_http"
  - "term_glyph"
  - "test_api"
  - "typed_data"
  - "vector_math"
  - "webdriver"
